[package]
name = "skald"
version = "0.1.0"
authors = ["Jack Stanek <stane064@umn.edu>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.17.0"

[dependencies]
lalrpop-util = "0.17.0"
regex = "0.2.1"
rustyline = "4.1.0"